### ISSUE TITLE
Updating QA vector tiles

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim-Data-Analyser#10]
We generate about 3.5G of vector tiles at the moment which need to be updated daily.

One obvious update strategy would be to just overwrite the existing tiles with new ones. But this may leave 'ghost tiles' where data has gone and no new tile is generated. So old data needs to be deleted. Removing the entire data set before regenerating the new one is not an option because then the vector tiles would not be accessible while the new ones are generated. That means the new tiles need to be generated in a temporary location and then switch the new tile. This is a workable solution for now but means that every day 3.5G of data needs to be deleted, which takes quite a bit of time because the directory consists of lots of small files.

It would be nice if the vector tile generator could support in-place updates that overwrites existing tiles and deletes ghost tiles if needed. Bonus points if it also just not writes new tiles when the content hasn't changed.

**Comment by AntoJvlt** [comment]
We can directly add this logic to the clustering-vt algorithm. While iterating on all possible tiles coordinates, if there is no feature in one tile (generated by supercluster) instead of just doing nothing we can check if there is a pbf file at the given output_folder `output_folder/z/x/y.pbf`. If this is the case we can delete it. By doing that, no need to remove the entire vector tiles folder (for a one rule) before generating the tiles. We also should check if that doesn't increase the execution time to much.

However If we want to write new tiles only if the content has changed we need to check if there is already a .pbf file, then we need to decode it and then we can compare. I think it might be faster to write the new content anyways to the file even if it has changed, but I may be wrong on that.

**Comment by lonvia** [comment]
One problem with writing is that it puts a strain on disks. This might or might not be a problem in practise (we haven't managed to wear out a SDD with Nominatim yet and it writes a lot). You might get away with creating a tile and comparing a hash if there is a guarantee that the features are always ordered the same. But this is all blue sky thinking. The in-place updates with deleting would be the important part.

**Comment by AntoJvlt** [comment]
With the optimized algorithm we now have to generate the vector tiles (in clustering-vt) we are not exploring child tiles which do not need to be generated. Hence, we can't check for existing pbf files for these tiles to delete them recursively. See #14.
I made some tests and going done through the child tiles which should be ignored only to try deleting the old pbf files increases the processing time quite a lot. I don't know if the trade-off between this execution time and limiting the strain on disks is worth it.

Also with the recent update on the tiles generation algorithm, I am pretty sure we have reduced the amount of file produced, are we still around 3.5G of vector tiles?

**Comment by lonvia** [comment]
Last night's vector tiles sum up to 6.4G.

If you optimise the tile generation through tree processing, you should be able to do the same with deletion: check if a tile exists that shouldn't. If it exists, delete it and repeat the process with its four child tiles. If it doesn't exist, stop. That should result in a single file-exists check for most cases.

**Comment by AntoJvlt** [comment]
You are absolutely right, I totally missed this obvious optimization of stopping the recursion when we can't find a file to delete as we already do for generating the tiles. This should do it I will work on that later.

Thanks.
